services:
  essence_parser:
    image: essence_parser:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: essence_parser
    ports:
      - "8091:8091/tcp"
    networks:
      - essence_network


networks:
  essence_network:
    driver: bridge
