# services:
#   postgres:
#     image: postgres:15-alpine
#     container_name: essense_db
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "5432:5432"
#     volumes:
#       - essense_postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 10s
#       timeout: 10s
#       retries: 5

  # elasticsearch:
  #   image: elasticsearch:7.17.4
  #   volumes:
  #     - ./elastic_search/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #     - elasticsearch:/usr/share/elasticsearch/data
  #     - elasticsearch:/var/lib/elasticsearch/data
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx512m -Xms512m"
  #     ELASTIC_USERNAME: "elastic"
  #     ELASTIC_PASSWORD: "MyPw123"
  #     discovery.type: single-node
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  # logstash:
  #   image: logstash:7.17.4
  #   volumes:
  #     - ./elastic_search/elk/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./elastic_search/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
  #   ports:
  #     - "5555:5555"
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   image: kibana:7.17.4
  #   volumes:
  #     - ./elastic_search/elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

volumes:
  elasticsearch:
  essense_postgres_data:

networks:
  essense:
